version: '3'

services:
  api:
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - ${DOCKER_COMPOSE_API_PORTS}
  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
